window.TRACKER_DATA = {
  updated_at: "2026-06-29T12:00:00-04:00",
  newsletter: {
    form_action: "https://fortlauderdalesignal.us2.list-manage.com/subscribe/post",
    form_u: "224e87bfc7d2cd51e4b2f70a4",
    form_id: "9f42bf570e",
    email_field: "MERGE0",
    bot_fields: ["b_name", "b_email"]
  },
  feeds: {
    public_monitor_url: ""
  },
  status: [
    {
      label: "Sites in the statewide picture",
      value: "19+",
      detail: "Operating, planned, proposed or under development",
      source_name: "Cleanview",
      source_url: "https://cleanview.co/data-centers/michigan"
    },
    {
      label: "Local pauses",
      value: "32+",
      detail: "Communities reported with temporary moratoria",
      source_name: "Michigan Public",
      source_url: "https://www.michiganpublic.org/environment-climate-change/2026-06-10/as-data-centers-expand-in-michigan-so-do-environmental-and-economic-concerns"
    },
    {
      label: "Saline campus scale",
      value: "1.4 GW",
      detail: "Planned power scale for the campus under construction",
      source_name: "Engineering News-Record",
      source_url: "https://www.enr.com/articles/63087-record-16b-data-center-project-advances-in-michigan"
    },
    {
      label: "Large-load threshold",
      value: "100 MW",
      detail: "Consumers Energy’s approved data center tariff threshold",
      source_name: "Michigan PSC",
      source_url: "https://www.michigan.gov/mpsc/commission/news-releases/2025/11/06/mpsc-approves-terms-of-service-between-consumers-energy-and-data-centers"
    }
  ],
  latest_developments: [
    {
      headline: "State Capitol rally brings Michigan’s data center debate into public view",
      summary: "A bipartisan group of speakers is scheduled to gather Tuesday evening in Lansing to press for changes in state data center policy.",
      published_date: "2026-06-22",
      source_name: "Sen. Jim Runestad on X",
      source_url: "https://x.com/SenJRunestad/status/2069178837577953448",
      region: "Statewide",
      topic: "Public event"
    },
    {
      headline: "Van Buren Township’s Google proposal enters a consequential wetland review",
      summary: "A permit under state review says the proposed one-gigawatt campus would permanently affect 13.55 acres of wetlands, with public comments open through June 26.",
      published_date: "2026-06-17",
      source_name: "Planet Detroit",
      source_url: "https://planetdetroit.org/2026/06/google-data-center-wetlands/",
      region: "Metro Detroit",
      topic: "Environment"
    },
    {
      headline: "Michigan’s local data center pauses now reach roughly 50 communities",
      summary: "Temporary moratoria continue to spread as municipalities study zoning, energy, water and infrastructure questions before accepting new applications.",
      published_date: "2026-06-10",
      source_name: "Michigan Public",
      source_url: "https://www.michiganpublic.org/environment-climate-change/2026-06-10/as-data-centers-expand-in-michigan-so-do-environmental-and-economic-concerns",
      region: "Statewide",
      topic: "Local policy"
    },
    {
      headline: "Allen Park planners turn down a 26-megawatt proposal and seek time for new rules",
      summary: "The planning commission voted 7–2 against the preliminary Solstice Data plan and recommended a six-month citywide pause while standards are developed.",
      published_date: "2026-06-05",
      source_name: "Planet Detroit",
      source_url: "https://planetdetroit.org/2026/06/allen-park-planners-reject-data-center/",
      region: "Metro Detroit",
      topic: "Zoning"
    },
    {
      headline: "Proposed Senate package would halt new data center approvals for one year",
      summary: "Senate Bills 1018–1020 would pause projects and related approvals while lawmakers review possible effects on ratepayers, communities and natural resources.",
      published_date: "2026-06-04",
      source_name: "Michigan Advance",
      source_url: "https://michiganadvance.com/briefs/runestad-proposes-one-year-moratorium-on-data-centers-urging-caution-and-scrutiny/",
      region: "Statewide",
      topic: "Legislation"
    },
    {
      headline: "A Mason-area proposal asks for city utilities and promises at least $1 billion in investment",
      summary: "An unidentified developer is pursuing utility service for a site west of Mason as residents and officials weigh noise, water and tax questions.",
      published_date: "2026-06-03",
      source_name: "WILX",
      source_url: "https://www.wilx.com/2026/06/03/data-center-developer-requests-mason-utilities-promises-1b-investment/",
      region: "Mid-Michigan",
      topic: "Project"
    },
    {
      headline: "Saline’s 1.4-gigawatt campus moves from approvals into full construction",
      summary: "The Related Digital campus for Oracle and OpenAI held a June 1 groundbreaking after construction began in February on the 250-acre site.",
      published_date: "2026-06-02",
      source_name: "Engineering News-Record",
      source_url: "https://www.enr.com/articles/63087-record-16b-data-center-project-advances-in-michigan",
      region: "Southeast Michigan",
      topic: "Construction"
    }
  ],
  meetings: [
    {
      title: "Wixom Planning Commission — Special Meeting & Public Hearing",
      body: "Public hearing on zoning ordinance amendments to define and regulate data centers. One of the first Michigan communities moving from moratorium to permanent rules.",
      government_body: "Wixom Planning Commission",
      county: "Oakland",
      start: "2026-06-29T19:00:00-04:00",
      location: "Wixom Council Chambers · 49045 Pontiac Trail, Wixom MI 48393",
      agenda_url: "https://www.wixomgov.org/home/showpublisheddocument/12830",
      watch_url: "https://www.youtube.com/channel/UCDAiD7kmuJQaB27m_PXUenA",
      source_url: "https://www.wixomgov.org/departments/construction-development-services-building/data-center-moratorium-ordinance"
    },

    {
      title: "Lyon Township Regular Board Meeting",
      body: "Regular board meeting. Lyon Township is in a high-growth Oakland County corridor. Stream link usually posted to their YouTube channel before the meeting.",
      government_body: "Lyon Township Board",
      county: "Oakland",
      start: "2026-07-07T19:00:00-04:00",
      location: "Lyon Township Hall · 58800 Grand River Ave, New Hudson MI 48165",
      agenda_url: "",
      watch_url: "https://www.youtube.com/channel/UC5JDLDMzIKAwR2YfY42miFw",
      source_url: "https://lyontownship.org/government/board-of-trustees/"
    },
    {
      title: "Pittsfield Charter Township Planning Commission",
      body: "Regular planning commission meeting. Pittsfield has been drafting a data center zoning ordinance. Agenda posted to their Agenda Center a few days before. No livestream available.",
      government_body: "Pittsfield Charter Township Planning Commission",
      county: "Washtenaw",
      start: "2026-07-07T19:00:00-04:00",
      location: "Pittsfield Township Hall · 6201 W. Michigan Ave, Ann Arbor MI 48108",
      agenda_url: "https://www.pittsfield-mi.gov/AgendaCenter",
      watch_url: "",
      source_url: "https://www.pittsfield-mi.gov/AgendaCenter"
    },
    {
      title: "Saline Township Regular Board Meeting",
      body: "Regular board meeting for the township hosting The Barn — Michigan's highest-profile active data center project. Construction updates may surface here. No livestream available.",
      government_body: "Saline Township Board",
      county: "Washtenaw",
      start: "2026-07-08T19:00:00-04:00",
      location: "Saline Township Hall · 5731 Braun Road, Saline MI 48176",
      agenda_url: "https://salinetownship.org/meeting-agendas.php",
      watch_url: "",
      source_url: "https://salinetownship.org/meeting-agendas.php"
    },

    {
      title: "Lenox Township Regular Board Meeting",
      body: "Regular board meeting. Lenox Township enacted an early moratorium on data centers. Check their Agenda Center closer to the date for posted items.",
      government_body: "Lenox Township Board",
      county: "Macomb",
      start: "2026-07-09T19:00:00-04:00",
      location: "Lenox Township Hall · 6675 25 Mile Rd, Ray MI 48096",
      agenda_url: "https://www.lenox-mi.gov/agendacenter",
      watch_url: "",
      source_url: "https://www.lenox-mi.gov/agendacenter"
    },
    {
      title: "Michigan Public Service Commission — Open Meeting",
      body: "Regular MPSC open meeting. Oversees large-load electric service agreements governing data center power contracts. Agenda and YouTube stream link typically posted 1–2 days before.",
      government_body: "Michigan Public Service Commission",
      county: "Ingham",
      start: "2026-07-10T09:30:00-04:00",
      location: "MPSC Offices · 7109 W. Saginaw Hwy, Lansing MI 48917",
      agenda_url: "https://www.michigan.gov/mpsc/commission/meetings",
      watch_url: "https://www.youtube.com/@MichiganPSC",
      source_url: "https://www.michigan.gov/mpsc/commission/meetings"
    }
  ],
  public_sources: [
    {
      account_name: "Sen. Jim Runestad",
      platform: "Facebook",
      platform_type: "social",
      posted_at: "2026-06-24",
      text: "Moratorium momentum is growing after the \"People over Data Centers\" Capitol rally. Criticized big money interests pushing data center projects on Michigan communities.",
      post_url: "https://www.facebook.com/SenJimRunestad/posts/people-over-data-centersour-push-for-a-moratorium-is-gaining-major-momentum/1461017315832317/"
    },
    {
      account_name: "Tom Leonard",
      platform: "Facebook",
      platform_type: "social",
      posted_at: "2026-06-24",
      text: "Renewed his call for a one-year moratorium, arguing it would force lawmakers to address energy costs, water use, and tax break transparency before new projects advance.",
      post_url: "https://www.facebook.com/TomLeonard28/posts/this-is-why-i-called-for-a-one-year-moratorium-on-new-data-centers-in-january/1606836081068249/"
    },
    {
      account_name: "Senate Democrats",
      platform: "Official statement",
      platform_type: "official",
      posted_at: "2026-06-25",
      text: "Detailed an eight-bill package covering water use caps, labor protections, and a ban on local officials signing NDAs with data center developers.",
      post_url: "https://senatedems.com/bayer/data-centers/"
    },
    {
      account_name: "City of Wixom",
      platform: "Official notice",
      platform_type: "official",
      posted_at: "2026-06-25",
      text: "Announced a June 29 public hearing on zoning amendments to define data centers and set performance standards for water use and noise.",
      post_url: "https://www.wixomgov.org/departments/construction-development-services-building/data-center-moratorium-ordinance"
    },
    {
      account_name: "Michigan Advance",
      platform: "News",
      platform_type: "news",
      posted_at: "2026-06-24",
      text: "Bipartisan lawmakers and residents rallied at the State Capitol calling for a one-year moratorium to study data center impacts on energy, water, and communities.",
      post_url: "https://michiganadvance.com/2026/06/24/michigan-lawmakers-residents-renew-push-for-statewide-data-center-moratorium/"
    },
    {
      account_name: "WEMU",
      platform: "News",
      platform_type: "news",
      posted_at: "2026-06-25",
      text: "Noted unusually broad bipartisan opposition at the Capitol rally. Sen. Runestad said he has rarely seen such a coalition form against a single development category.",
      post_url: "https://www.wemu.org/michigan-news/2026-06-25/michigan-lawmakers-continue-call-for-data-center-moratorium"
    }
  ],
  regional_watch: {
    statewide: [0, 2, 5],
    metro_detroit: [1, 3],
    west_michigan: [],
    mid_michigan: [5],
    northern_michigan: []
  },
  map_points: [
  {
    "name": "Saline Township campus (Stargate)",
    "municipality": "Saline Township",
    "county": "Washtenaw",
    "status": "Under construction",
    "layer": "projects",
    "developer": "Related Digital / Oracle / OpenAI",
    "power_mw": "1,400",
    "latitude": 42.166,
    "longitude": -83.782,
    "source_url": "https://www.enr.com/articles/63087-record-16b-data-center-project-advances-in-michigan",
    "source_name": "Engineering News-Record",
    "verified_date": "2026-06-02",
    "confidence": "Confirmed",
    "note": "250-acre build on 575-acre property. Full construction targeted early 2026."
  },
  {
    "name": "Van Buren Township Google proposal",
    "municipality": "Van Buren Township",
    "county": "Wayne",
    "status": "Proposed",
    "layer": "projects",
    "developer": "Google (Project Cannoli)",
    "power_mw": "1,000",
    "latitude": 42.232,
    "longitude": -83.486,
    "source_url": "https://planetdetroit.org/2026/06/google-data-center-wetlands/",
    "source_name": "Planet Detroit",
    "verified_date": "2026-06-17",
    "confidence": "Confirmed",
    "note": "~280 acres near Belleville. State wetland permit review pending."
  },
  {
    "name": "Lyon Township Project Flex",
    "municipality": "Lyon Township",
    "county": "Oakland",
    "status": "Conditionally approved",
    "layer": "projects",
    "developer": "Verrus / Walbridge",
    "power_mw": "",
    "latitude": 42.52,
    "longitude": -83.65,
    "source_url": "https://www.crainsdetroit.com/economic-development/verrus-data-center-planned-lyon-township",
    "source_name": "Crain's Detroit",
    "verified_date": "2025-09-01",
    "confidence": "Reported",
    "note": "~172 acres, 1.8M sq ft. Alphabet-backed Sidewalk Infrastructure ties reported."
  },
  {
    "name": "Southfield Metrobloks data center",
    "municipality": "Southfield",
    "county": "Oakland",
    "status": "Approved",
    "layer": "projects",
    "developer": "Metrobloks",
    "power_mw": "100",
    "latitude": 42.473,
    "longitude": -83.221,
    "source_url": "https://www.mlive.com/news/2025/12/100k-square-foot-data-center-proposed-for-vacant-southfield-parcel-near-i-696.html",
    "source_name": "MLive",
    "verified_date": "2025-12-16",
    "confidence": "Confirmed",
    "note": "~110,000 sq ft near I-696. City council approved site plan Dec. 2025."
  },
  {
    "name": "Allen Park Solstice proposal",
    "municipality": "Allen Park",
    "county": "Wayne",
    "status": "Rejected by planning commission",
    "layer": "projects",
    "developer": "Solstice Data",
    "power_mw": "26",
    "latitude": 42.257,
    "longitude": -83.211,
    "source_url": "https://planetdetroit.org/2026/06/allen-park-planners-reject-data-center/",
    "source_name": "Planet Detroit",
    "verified_date": "2026-06-05",
    "confidence": "Confirmed",
    "note": "Planning commission voted 7\u20132 against; city recommended 6-month pause."
  },
  {
    "name": "Mason-area proposal",
    "municipality": "Mason area",
    "county": "Ingham",
    "status": "Proposed",
    "layer": "projects",
    "developer": "Undisclosed",
    "power_mw": "",
    "latitude": 42.58,
    "longitude": -84.443,
    "source_url": "https://www.wilx.com/2026/06/03/data-center-developer-requests-mason-utilities-promises-1b-investment/",
    "source_name": "WILX",
    "verified_date": "2026-06-03",
    "confidence": "Reported",
    "note": "Developer requested city utilities; $1B investment pledged."
  },
  {
    "name": "Howell Township Meta proposal",
    "municipality": "Howell Township",
    "county": "Livingston",
    "status": "Withdrawn",
    "layer": "projects",
    "developer": "Randee LLC / Meta (reported)",
    "power_mw": "",
    "latitude": 42.607,
    "longitude": -84.089,
    "source_url": "https://www.mlive.com/news/ann-arbor/2025/12/rezoning-request-for-meta-backed-data-center-near-howell-withdrawn-officials-say.html",
    "source_name": "MLive",
    "verified_date": "2025-12-08",
    "confidence": "Reported",
    "note": "1,000+ acre proposal withdrawn Dec. 2025 amid opposition."
  },
  {
    "name": "Augusta Township Thor Equities",
    "municipality": "Augusta Township",
    "county": "Washtenaw",
    "status": "Approved",
    "layer": "projects",
    "developer": "Thor Equities",
    "power_mw": "",
    "latitude": 42.11,
    "longitude": -83.74,
    "source_url": "https://www.mlive.com/news/ann-arbor/2025/07/farmland-rezoned-for-proposed-1b-data-center-in-southeast-washtenaw-county.html",
    "source_name": "MLive",
    "verified_date": "2025-07-01",
    "confidence": "Confirmed",
    "note": "522 acres rezoned within 810-acre site. Referendum expected 2026."
  },
  {
    "name": "York Township Sansone / Toyota land",
    "municipality": "York Township",
    "county": "Washtenaw",
    "status": "Proposed",
    "layer": "projects",
    "developer": "Sansone Group",
    "power_mw": "",
    "latitude": 42.14,
    "longitude": -83.85,
    "source_url": "https://www.mlive.com/news/ann-arbor/2025/12/developers-seek-another-ai-data-center-on-land-owned-by-toyota-south-of-ann-arbor.html",
    "source_name": "MLive",
    "verified_date": "2025-12-01",
    "confidence": "Reported",
    "note": "412 acres off Platt Road. No formal township application yet."
  },
  {
    "name": "Ypsilanti Township UM / Los Alamos facility",
    "municipality": "Ypsilanti Township",
    "county": "Washtenaw",
    "status": "Under review",
    "layer": "projects",
    "developer": "University of Michigan / Los Alamos",
    "power_mw": "",
    "latitude": 42.24,
    "longitude": -83.61,
    "source_url": "https://www.mlive.com/news/ann-arbor/2024/12/price-tag-is-12b-for-university-of-michigan-los-alamos-project-to-build-fastest-computer.html",
    "source_name": "MLive",
    "verified_date": "2025-12-01",
    "confidence": "Reported",
    "note": "$1.2B high-performance computing facility. Township opposes Textile Road site."
  },
  {
    "name": "Gaines Township Microsoft",
    "municipality": "Gaines Township",
    "county": "Kent",
    "status": "Proposed",
    "layer": "projects",
    "developer": "Microsoft",
    "power_mw": "",
    "latitude": 42.85,
    "longitude": -85.68,
    "source_url": "https://www.mlive.com/news/grand-rapids/2025/12/microsoft-confirms-data-center-plans-in-kent-county.html",
    "source_name": "MLive",
    "verified_date": "2025-12-01",
    "confidence": "Confirmed",
    "note": "316-acre former Steelcase property. Rezoning hearing Dec. 2025."
  },
  {
    "name": "Dorr Township Microsoft",
    "municipality": "Dorr Township",
    "county": "Allegan",
    "status": "Proposed",
    "layer": "projects",
    "developer": "Microsoft",
    "power_mw": "",
    "latitude": 42.72,
    "longitude": -85.75,
    "source_url": "https://www.crainsgrandrapids.com/news/real-estate/microsoft-buys-a-second-large-property-in-west-michigan-for-potential-data-center/",
    "source_name": "Crain's Grand Rapids",
    "verified_date": "2024-01-01",
    "confidence": "Reported",
    "note": "272 acres along U.S. 131. No formal plan filed."
  },
  {
    "name": "Lowell Township Franklin Partners",
    "municipality": "Lowell Township",
    "county": "Kent",
    "status": "Proposed",
    "layer": "projects",
    "developer": "Franklin Partners",
    "power_mw": "",
    "latitude": 42.93,
    "longitude": -85.34,
    "source_url": "https://www.mlive.com/news/grand-rapids/2025/12/controversial-1b-kent-county-data-center-faces-public-hearing-in-january.html",
    "source_name": "MLive",
    "verified_date": "2025-12-01",
    "confidence": "Reported",
    "note": "235-acre parcel. Tenant described as top-10 U.S. company."
  },
  {
    "name": "Pavilion Township Franklin Partners",
    "municipality": "Pavilion Township",
    "county": "Kalamazoo",
    "status": "Withdrawn",
    "layer": "projects",
    "developer": "Franklin Partners",
    "power_mw": "",
    "latitude": 42.3,
    "longitude": -85.52,
    "source_url": "https://www.mlive.com/news/kalamazoo/2025/11/data-center-plans-near-kalamazoo-put-on-hold-after-community-backlash.html",
    "source_name": "MLive",
    "verified_date": "2025-11-01",
    "confidence": "Confirmed",
    "note": "265-acre industrial site. Request withdrawn after backlash."
  },
  {
    "name": "Lansing Deep Green data center",
    "municipality": "Lansing",
    "county": "Ingham",
    "status": "Proposed",
    "layer": "projects",
    "developer": "Deep Green",
    "power_mw": "24",
    "latitude": 42.732,
    "longitude": -84.555,
    "source_url": "https://www.lbwl.com/community/newsroom/2025-11-05-deep-green-proposes-120-million-sustainable-data-center-investment",
    "source_name": "Lansing BWL",
    "verified_date": "2025-11-05",
    "confidence": "Confirmed",
    "note": "$120M downtown project. Partners with BWL for district heat."
  },
  {
    "name": "Frenchtown Township Project Cherry Blossom",
    "municipality": "Frenchtown Township",
    "county": "Monroe",
    "status": "Proposed",
    "layer": "projects",
    "developer": "Cloverleaf",
    "power_mw": "",
    "latitude": 41.92,
    "longitude": -83.38,
    "source_url": "https://www.mlive.com/news/ann-arbor/2025/11/proposed-ai-data-center-in-monroe-county-faces-community-pushback.html",
    "source_name": "MLive",
    "verified_date": "2025-11-01",
    "confidence": "Reported",
    "note": "200-acre former golf course near I-75."
  },
  {
    "name": "Dundee Township Project Ironwood",
    "municipality": "Dundee Township",
    "county": "Monroe",
    "status": "Proposed",
    "layer": "projects",
    "developer": "Cloverleaf",
    "power_mw": "",
    "latitude": 41.96,
    "longitude": -83.66,
    "source_url": "https://www.monroenews.com/story/news/2025/11/26/dundee-township-data-center-continues-to-be-hot-topic/87479493007/",
    "source_name": "Monroe News",
    "verified_date": "2025-11-26",
    "confidence": "Reported",
    "note": "350-acre site. Township has temporary moratorium."
  },
  {
    "name": "Kalkaska County Rocklocker proposal",
    "municipality": "Kalkaska area",
    "county": "Kalkaska",
    "status": "Withdrawn",
    "layer": "projects",
    "developer": "Rocklocker LLC",
    "power_mw": "",
    "latitude": 44.73,
    "longitude": -85.18,
    "source_url": "https://www.mlive.com/environment/2025/11/northern-michigan-data-center-idea-scrapped-following-community-rejection.html",
    "source_name": "MLive",
    "verified_date": "2025-11-01",
    "confidence": "Confirmed",
    "note": "Proposal scrapped after community rejection."
  },
  {
    "name": "Springfield Township 84-acre campus",
    "municipality": "Springfield Township",
    "county": "Oakland",
    "status": "Proposed",
    "layer": "projects",
    "developer": "Undisclosed",
    "power_mw": "",
    "latitude": 42.75,
    "longitude": -83.48,
    "source_url": "https://www.detroitnews.com/story/news/local/oakland-county/2026/01/07/springfield-twp-passes-temporary-data-center-moratorium/88049214007/",
    "source_name": "Detroit News",
    "verified_date": "2026-01-07",
    "confidence": "Reported",
    "note": "84-acre proposed campus triggered 180-day moratorium."
  },
  {
    "name": "City of Northville moratorium",
    "municipality": "Northville",
    "county": "Wayne",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.431,
    "longitude": -83.483,
    "source_url": "https://www.wxyz.com/news/data-centers/northville-city-council-unanimously-approves-12-month-data-center-moratorium",
    "source_name": "WXYZ",
    "verified_date": "2026-01-06",
    "confidence": "Confirmed",
    "note": "12-month preemptive moratorium."
  },
  {
    "name": "Springfield Township moratorium",
    "municipality": "Springfield Township",
    "county": "Oakland",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.755,
    "longitude": -83.485,
    "source_url": "https://www.detroitnews.com/story/news/local/oakland-county/2026/01/07/springfield-twp-passes-temporary-data-center-moratorium/88049214007/",
    "source_name": "Detroit News",
    "verified_date": "2026-01-07",
    "confidence": "Confirmed",
    "note": "180-day moratorium."
  },
  {
    "name": "City of Pontiac moratorium",
    "municipality": "Pontiac",
    "county": "Oakland",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.638,
    "longitude": -83.291,
    "source_url": "https://www.detroitnews.com/story/news/local/oakland-county/2026/01/21/pontiac-latest-community-to-pass-data-center-moratorium/88286730007/",
    "source_name": "Detroit News",
    "verified_date": "2026-01-21",
    "confidence": "Confirmed",
    "note": "6-month moratorium."
  },
  {
    "name": "City of Sterling Heights moratorium",
    "municipality": "Sterling Heights",
    "county": "Macomb",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.58,
    "longitude": -83.03,
    "source_url": "https://www.detroitnews.com/story/news/local/macomb-county/2026/02/03/sterling-heights-passes-moratorium-on-data-centers/88493407007/",
    "source_name": "Detroit News",
    "verified_date": "2026-02-04",
    "confidence": "Confirmed",
    "note": "1-year moratorium."
  },
  {
    "name": "City of Detroit moratorium (proposed)",
    "municipality": "Detroit",
    "county": "Wayne",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.331,
    "longitude": -83.046,
    "source_url": "https://planetdetroit.org/2026/04/detroit-data-center-zoning/",
    "source_name": "Planet Detroit",
    "verified_date": "2026-04-16",
    "confidence": "Reported",
    "note": "Council voted 6\u20132 to request 2-year moratorium. Mayor convened working group."
  },
  {
    "name": "Ypsilanti Township water moratorium",
    "municipality": "Ypsilanti Township",
    "county": "Washtenaw",
    "status": "Utility pause",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.245,
    "longitude": -83.62,
    "source_url": "https://planetdetroit.org/2026/04/data-center-water-moratorium-ypsilanti/",
    "source_name": "Planet Detroit",
    "verified_date": "2026-04-22",
    "confidence": "Confirmed",
    "note": "YCUA 12-month pause on water/sewer for new data centers."
  },
  {
    "name": "City of Ypsilanti moratorium",
    "municipality": "Ypsilanti",
    "county": "Washtenaw",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.241,
    "longitude": -83.613,
    "source_url": "https://www.wemu.org/wemu-news/2026-03-04/city-of-ypsilanti-passes-data-center-moratorium",
    "source_name": "WEMU",
    "verified_date": "2026-03-03",
    "confidence": "Confirmed",
    "note": "60-day emergency + 365-day resolution."
  },
  {
    "name": "City of East Lansing moratorium",
    "municipality": "East Lansing",
    "county": "Ingham",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.737,
    "longitude": -84.484,
    "source_url": "https://www.wkar.org/wkar-news/2026-03-18/east-lansing-passes-data-center-moratorium-while-evaluating-zoning-ordinances",
    "source_name": "WKAR",
    "verified_date": "2026-03-17",
    "confidence": "Confirmed",
    "note": "6-month preemptive moratorium."
  },
  {
    "name": "Armada Township moratorium",
    "municipality": "Armada Township",
    "county": "Macomb",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.845,
    "longitude": -82.884,
    "source_url": "https://www.wkar.org/wkar-news/2026-02-27/michigan-data-center-tracker-moratoria-legislation-and-grid-impact",
    "source_name": "WKAR",
    "verified_date": "2026-01-14",
    "confidence": "Confirmed",
    "note": "180-day moratorium."
  },
  {
    "name": "Dundee Township moratorium",
    "municipality": "Dundee Township",
    "county": "Monroe",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 41.965,
    "longitude": -83.655,
    "source_url": "https://bridgemi.com/michigan-environment-watch/at-least-19-michigan-towns-pause-data-centers-no-one-knows-if-itll-work/",
    "source_name": "Bridge Michigan",
    "verified_date": "2025-10-01",
    "confidence": "Reported",
    "note": "90-day moratorium, subsequently extended."
  },
  {
    "name": "Grand Blanc Township moratorium",
    "municipality": "Grand Blanc Township",
    "county": "Genesee",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.927,
    "longitude": -83.629,
    "source_url": "https://www.wkar.org/wkar-news/2026-02-27/michigan-data-center-tracker-moratoria-legislation-and-grid-impact",
    "source_name": "WKAR",
    "verified_date": "2026-01-21",
    "confidence": "Confirmed",
    "note": "1-year moratorium."
  },
  {
    "name": "Green Charter Township moratorium",
    "municipality": "Green Charter Township",
    "county": "Mecosta",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 43.25,
    "longitude": -85.75,
    "source_url": "https://www.wkar.org/wkar-news/2026-02-27/michigan-data-center-tracker-moratoria-legislation-and-grid-impact",
    "source_name": "WKAR",
    "verified_date": "2025-12-09",
    "confidence": "Confirmed",
    "note": "1-year moratorium."
  },
  {
    "name": "Hayes Township moratorium",
    "municipality": "Hayes Township",
    "county": "Charlevoix",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 45.28,
    "longitude": -85.1,
    "source_url": "https://www.interlochenpublicradio.org/ipr-news/2026-02-10/charlevoix-area-township-passes-data-center-moratorium",
    "source_name": "IPR",
    "verified_date": "2026-02-10",
    "confidence": "Confirmed",
    "note": "180-day moratorium."
  },
  {
    "name": "Lenox Township moratorium",
    "municipality": "Lenox Township",
    "county": "Macomb",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.694,
    "longitude": -82.804,
    "source_url": "https://www.wkar.org/wkar-news/2026-02-27/michigan-data-center-tracker-moratoria-legislation-and-grid-impact",
    "source_name": "WKAR",
    "verified_date": "2026-02-02",
    "confidence": "Confirmed",
    "note": "4-month moratorium with extension option."
  },
  {
    "name": "Lodi Township moratorium",
    "municipality": "Lodi Township",
    "county": "Washtenaw",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.18,
    "longitude": -84.08,
    "source_url": "https://www.wkar.org/wkar-news/2026-02-27/michigan-data-center-tracker-moratoria-legislation-and-grid-impact",
    "source_name": "WKAR",
    "verified_date": "2026-02-03",
    "confidence": "Confirmed",
    "note": "180-day moratorium."
  },
  {
    "name": "Manchester Township moratorium",
    "municipality": "Manchester Township",
    "county": "Washtenaw",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.15,
    "longitude": -84.04,
    "source_url": "https://themanchestermirror.com/2026/02/09/data-center-moratoriums-pile-up-in-michigan-no-one-knows-if-theyll-work/",
    "source_name": "Manchester Mirror",
    "verified_date": "2025-10-14",
    "confidence": "Confirmed",
    "note": "2-year moratorium."
  },
  {
    "name": "Pittsfield Township moratorium",
    "municipality": "Pittsfield Township",
    "county": "Washtenaw",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.25,
    "longitude": -83.72,
    "source_url": "https://www.wkar.org/wkar-news/2026-02-27/michigan-data-center-tracker-moratoria-legislation-and-grid-impact",
    "source_name": "WKAR",
    "verified_date": "2025-11-18",
    "confidence": "Confirmed",
    "note": "180-day moratorium."
  },
  {
    "name": "City of Saginaw moratorium",
    "municipality": "Saginaw",
    "county": "Saginaw",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 43.419,
    "longitude": -83.951,
    "source_url": "https://www.wnem.com/2026/01/13/city-saginaw-placing-moratorium-data-centers/",
    "source_name": "WNEM",
    "verified_date": "2026-01-13",
    "confidence": "Confirmed",
    "note": "6-month moratorium, unanimous."
  },
  {
    "name": "City of Saline moratorium",
    "municipality": "Saline",
    "county": "Washtenaw",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.167,
    "longitude": -83.781,
    "source_url": "https://www.wkar.org/wkar-news/2026-02-27/michigan-data-center-tracker-moratoria-legislation-and-grid-impact",
    "source_name": "WKAR",
    "verified_date": "2026-01-12",
    "confidence": "Confirmed",
    "note": "12-month moratorium (city, separate from township campus)."
  },
  {
    "name": "City of South Lyon moratorium",
    "municipality": "South Lyon",
    "county": "Oakland",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.46,
    "longitude": -83.651,
    "source_url": "https://www.wkar.org/wkar-news/2026-02-27/michigan-data-center-tracker-moratoria-legislation-and-grid-impact",
    "source_name": "WKAR",
    "verified_date": "2026-02-01",
    "confidence": "Confirmed",
    "note": "12-month moratorium."
  },
  {
    "name": "Sylvan Township moratorium",
    "municipality": "Sylvan Township",
    "county": "Washtenaw",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.08,
    "longitude": -84.13,
    "source_url": "https://www.wkar.org/wkar-news/2026-02-27/michigan-data-center-tracker-moratoria-legislation-and-grid-impact",
    "source_name": "WKAR",
    "verified_date": "2026-01-01",
    "confidence": "Confirmed",
    "note": "6-month moratorium."
  },
  {
    "name": "City of Taylor moratorium",
    "municipality": "Taylor",
    "county": "Wayne",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.24,
    "longitude": -83.27,
    "source_url": "https://www.wkar.org/wkar-news/2026-02-27/michigan-data-center-tracker-moratoria-legislation-and-grid-impact",
    "source_name": "WKAR",
    "verified_date": "2026-01-01",
    "confidence": "Confirmed",
    "note": "1-year moratorium."
  },
  {
    "name": "Tyrone Township moratorium",
    "municipality": "Tyrone Township",
    "county": "Kent",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.74,
    "longitude": -83.63,
    "source_url": "https://www.wkar.org/wkar-news/2026-02-27/michigan-data-center-tracker-moratoria-legislation-and-grid-impact",
    "source_name": "WKAR",
    "verified_date": "2026-01-01",
    "confidence": "Confirmed",
    "note": "6-month moratorium."
  },
  {
    "name": "Ann Arbor Township moratorium",
    "municipality": "Ann Arbor Township",
    "county": "Washtenaw",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.3,
    "longitude": -83.72,
    "source_url": "https://www.wkar.org/wkar-news/2026-02-27/michigan-data-center-tracker-moratoria-legislation-and-grid-impact",
    "source_name": "WKAR",
    "verified_date": "2026-02-01",
    "confidence": "Confirmed",
    "note": "12-month moratorium."
  },
  {
    "name": "Erie Township moratorium",
    "municipality": "Erie Township",
    "county": "Monroe",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 41.8,
    "longitude": -83.5,
    "source_url": "https://www.wkar.org/wkar-news/2026-02-27/michigan-data-center-tracker-moratoria-legislation-and-grid-impact",
    "source_name": "WKAR",
    "verified_date": "2026-02-10",
    "confidence": "Confirmed",
    "note": "Limited moratorium."
  },
  {
    "name": "Meridian Township moratorium",
    "municipality": "Meridian Township",
    "county": "Ingham",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.72,
    "longitude": -84.41,
    "source_url": "https://www.wkar.org/wkar-news/2026-05-28/meridian-township-is-officially-putting-a-pause-on-any-data-centers-that-might-come-to-town",
    "source_name": "WKAR",
    "verified_date": "2026-05-19",
    "confidence": "Confirmed",
    "note": "6-month moratorium on data centers and battery storage."
  },
  {
    "name": "Washington Township moratorium",
    "municipality": "Washington Township",
    "county": "Macomb",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.77,
    "longitude": -83.03,
    "source_url": "https://www.detroitnews.com/story/news/local/macomb-county/2026/05/23/washington-township-passes-six-month-moratorium-on-data-centers/90213646007/",
    "source_name": "Detroit News",
    "verified_date": "2026-05-23",
    "confidence": "Confirmed",
    "note": "6-month moratorium."
  },
  {
    "name": "Stronach Township moratorium",
    "municipality": "Stronach Township",
    "county": "Manistee",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 44.215,
    "longitude": -86.292,
    "source_url": "https://www.manisteenews.com/news/article/stronach-township-approves-six-month-data-center-22301704.php",
    "source_name": "Manistee News Advocate",
    "verified_date": "2026-06-12",
    "confidence": "Confirmed",
    "note": "Six-month pause through Dec. 31, 2026."
  },
  {
    "name": "Filer Township moratorium",
    "municipality": "Filer Charter Township",
    "county": "Manistee",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 44.181,
    "longitude": -86.321,
    "source_url": "https://www.manisteenews.com/news/article/filer-township-approves-one-year-data-center-22282763.php",
    "source_name": "Manistee News Advocate",
    "verified_date": "2026-06-08",
    "confidence": "Confirmed",
    "note": "One-year moratorium."
  },
  {
    "name": "Big Rapids Township moratorium",
    "municipality": "Big Rapids Township",
    "county": "Mecosta",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 43.69,
    "longitude": -85.48,
    "source_url": "https://www.bigrapidsnews.com/news/article/big-rapids-township-michigan-enacts-temporary-21938856.php",
    "source_name": "Big Rapids Pioneer",
    "verified_date": "2026-02-23",
    "confidence": "Reported",
    "note": "One-year pause."
  },
  {
    "name": "City of Wixom moratorium",
    "municipality": "Wixom",
    "county": "Oakland",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 42.525,
    "longitude": -83.536,
    "source_url": "https://www.wixomgov.org/departments/construction-development-services-building/data-center-moratorium-ordinance",
    "source_name": "City of Wixom",
    "verified_date": "2026-06-25",
    "confidence": "Confirmed",
    "note": "Moving from moratorium to permanent zoning rules; June 29 hearing."
  },
  {
    "name": "Delta County moratorium (draft)",
    "municipality": "Delta County",
    "county": "Delta",
    "status": "Moratorium",
    "layer": "moratoria",
    "developer": "",
    "power_mw": "",
    "latitude": 45.77,
    "longitude": -86.91,
    "source_url": "https://www.uppermichiganssource.com/2026/04/07/delta-county-planning-commission-approves-data-center-moratorium-draft/",
    "source_name": "Upper Michigan's Source",
    "verified_date": "2026-04-07",
    "confidence": "Reported",
    "note": "Draft moratorium up to 12 months in legal review."
  },
  {
    "name": "Michigan State Capitol rally",
    "municipality": "Lansing",
    "county": "Ingham",
    "status": "Public signal",
    "layer": "policy",
    "developer": "",
    "power_mw": "",
    "latitude": 42.733,
    "longitude": -84.555,
    "source_url": "https://michiganadvance.com/2026/06/24/michigan-lawmakers-residents-renew-push-for-statewide-data-center-moratorium/",
    "source_name": "Michigan Advance",
    "verified_date": "2026-06-22",
    "confidence": "Confirmed",
    "note": "Bipartisan Capitol rally for statewide moratorium study."
  },
  {
    "name": "MPSC Consumers Energy data center tariff",
    "municipality": "Lansing",
    "county": "Ingham",
    "status": "Approved",
    "layer": "policy",
    "developer": "Consumers Energy",
    "power_mw": "100",
    "latitude": 42.725,
    "longitude": -84.62,
    "source_url": "https://www.michigan.gov/mpsc/commission/news-releases/2025/11/06/mpsc-approves-terms-of-service-between-consumers-energy-and-data-centers",
    "source_name": "Michigan PSC",
    "verified_date": "2025-11-06",
    "confidence": "Confirmed",
    "note": "100 MW large-load threshold for data center tariff."
  },
  {
    "name": "ITC Oneida substation (start)",
    "municipality": "Oneida Township",
    "county": "Eaton",
    "status": "Under review",
    "layer": "transmission",
    "developer": "ITC Michigan",
    "power_mw": "",
    "latitude": 42.695,
    "longitude": -84.872,
    "source_url": "https://www.michiganpublic.org/transportation-infrastructure/2025-12-22/routes-proposed-for-high-voltage-transmission-line-in-eaton-ingham-livingston-counties",
    "source_name": "Michigan Public",
    "verified_date": "2025-12-22",
    "confidence": "Confirmed",
    "note": "Western terminus of proposed 50-mile Oneida\u2013Sabine Lake corridor."
  },
  {
    "name": "ITC Sabine Lake substation (end)",
    "municipality": "near Fowlerville",
    "county": "Livingston",
    "status": "Under review",
    "layer": "transmission",
    "developer": "ITC Michigan",
    "power_mw": "",
    "latitude": 42.705,
    "longitude": -84.015,
    "source_url": "https://www.michiganpublic.org/transportation-infrastructure/2025-12-22/routes-proposed-for-high-voltage-transmission-line-in-eaton-ingham-livingston-counties",
    "source_name": "Michigan Public",
    "verified_date": "2025-12-22",
    "confidence": "Confirmed",
    "note": "Planned new substation northeast of Fowlerville."
  },
  {
    "name": "Grand Ledge corridor area",
    "municipality": "Grand Ledge",
    "county": "Eaton",
    "status": "Under review",
    "layer": "transmission",
    "developer": "ITC Michigan",
    "power_mw": "",
    "latitude": 42.755,
    "longitude": -84.746,
    "source_url": "https://www.wkar.org/wkar-news/2026-01-25/proposed-transmission-line-would-cross-15-townships-mid-michigan-residents-demand-answers-as-meetings-start-monday",
    "source_name": "WKAR",
    "verified_date": "2026-01-25",
    "confidence": "Reported",
    "note": "Proposed routes pass just southwest of Grand Ledge."
  },
  {
    "name": "Okemos listening session hub",
    "municipality": "Okemos",
    "county": "Ingham",
    "status": "Public meeting",
    "layer": "transmission",
    "developer": "ITC Michigan",
    "power_mw": "",
    "latitude": 42.717,
    "longitude": -84.427,
    "source_url": "https://www.wkar.org/wkar-news/2026-01-25/proposed-transmission-line-would-cross-15-townships-mid-michigan-residents-demand-answers-as-meetings-start-monday",
    "source_name": "WKAR",
    "verified_date": "2026-01-26",
    "confidence": "Confirmed",
    "note": "Community listening sessions Jan. 26\u201327 at Okemos Event Center."
  },
  {
    "name": "Wixom Planning Commission hearing",
    "municipality": "Wixom",
    "county": "Oakland",
    "status": "Public meeting",
    "layer": "meetings",
    "developer": "",
    "power_mw": "",
    "latitude": 42.525,
    "longitude": -83.536,
    "source_url": "https://www.wixomgov.org/departments/construction-development-services-building/data-center-moratorium-ordinance",
    "source_name": "City of Wixom",
    "verified_date": "2026-06-29",
    "confidence": "Confirmed",
    "note": "June 29 public hearing on permanent data center zoning rules."
  },
  {
    "name": "Lyon Township board meeting",
    "municipality": "Lyon Township",
    "county": "Oakland",
    "status": "Public meeting",
    "layer": "meetings",
    "developer": "",
    "power_mw": "",
    "latitude": 42.52,
    "longitude": -83.65,
    "source_url": "https://lyontownship.org/government/board-of-trustees/",
    "source_name": "Lyon Township",
    "verified_date": "2026-07-07",
    "confidence": "Confirmed",
    "note": "July 7 regular board meeting."
  },
  {
    "name": "Pittsfield Planning Commission",
    "municipality": "Pittsfield Township",
    "county": "Washtenaw",
    "status": "Public meeting",
    "layer": "meetings",
    "developer": "",
    "power_mw": "",
    "latitude": 42.25,
    "longitude": -83.72,
    "source_url": "https://www.pittsfield-mi.gov/AgendaCenter",
    "source_name": "Pittsfield Township",
    "verified_date": "2026-07-07",
    "confidence": "Confirmed",
    "note": "July 7 planning commission \u2014 drafting data center ordinance."
  },
  {
    "name": "Saline Township board meeting",
    "municipality": "Saline Township",
    "county": "Washtenaw",
    "status": "Public meeting",
    "layer": "meetings",
    "developer": "",
    "power_mw": "",
    "latitude": 42.166,
    "longitude": -83.782,
    "source_url": "https://salinetownship.org/meeting-agendas.php",
    "source_name": "Saline Township",
    "verified_date": "2026-07-08",
    "confidence": "Confirmed",
    "note": "July 8 board meeting \u2014 active construction updates possible."
  },
  {
    "name": "Lenox Township board meeting",
    "municipality": "Lenox Township",
    "county": "Macomb",
    "status": "Public meeting",
    "layer": "meetings",
    "developer": "",
    "power_mw": "",
    "latitude": 42.694,
    "longitude": -82.804,
    "source_url": "https://www.lenox-mi.gov/agendacenter",
    "source_name": "Lenox Township",
    "verified_date": "2026-07-09",
    "confidence": "Confirmed",
    "note": "July 9 board meeting."
  },
  {
    "name": "MPSC open meeting",
    "municipality": "Lansing",
    "county": "Ingham",
    "status": "Public meeting",
    "layer": "meetings",
    "developer": "",
    "power_mw": "",
    "latitude": 42.725,
    "longitude": -84.62,
    "source_url": "https://www.michigan.gov/mpsc/commission/meetings",
    "source_name": "Michigan PSC",
    "verified_date": "2026-07-10",
    "confidence": "Confirmed",
    "note": "July 10 open meeting \u2014 oversees large-load electric agreements."
  }
],
  map_meta: {
    version: "2026-06-29",
    record_count_note: "Every pin is sourced. Township-level coordinates unless noted.",
    external_map: {
      label: "ITC official route map",
      url: "https://www.mifuturegrid.com/oneida-sabine-lake/"
    }
  },
  map_stories: [
    {
      id: "itc-oneida-sabine",
      title: "50 miles of new power lines through Mid-Michigan",
      kicker: "Power & grid",
      summary: "ITC Michigan is proposing a high-voltage line from Oneida Township (southwest of Grand Ledge) to a new Sabine Lake substation near Fowlerville — crossing 15 townships in Eaton, Ingham and Livingston counties. Residents cite farmland, property values and transparency concerns as data center load drives grid upgrades.",
      region: "Mid-Michigan",
      source_name: "WKAR Public Media",
      source_url: "https://www.wkar.org/wkar-news/2026-01-25/proposed-transmission-line-would-cross-15-townships-mid-michigan-residents-demand-answers-as-meetings-start-monday",
      layer: "transmission",
      fly_to: { lat: 42.72, lng: -84.45, zoom: 9 }
    },
    {
      id: "moratorium-wave",
      title: "~50 communities have hit pause",
      kicker: "Local response",
      summary: "Temporary moratoria now cover an area comparable to Rhode Island, according to Michigan Public reporting. Townships and cities are studying zoning, water, noise and infrastructure before accepting new data center applications.",
      region: "Statewide",
      source_name: "Michigan Public",
      source_url: "https://www.michiganpublic.org/environment-climate-change/2026-06-10/as-data-centers-expand-in-michigan-so-do-environmental-and-economic-concerns",
      layer: "moratoria",
      fly_to: { lat: 43.0, lng: -84.5, zoom: 7 }
    },
    {
      id: "saline-stargate",
      title: "Saline Township: Michigan's first hyperscale build",
      kicker: "Active construction",
      summary: "Related Digital's 1.4 GW campus for Oracle and OpenAI broke ground in June 2026. DTE Energy is seeking MPSC approval for power contracts that critics warn could affect ratepayers.",
      region: "Southeast Michigan",
      source_name: "Engineering News-Record",
      source_url: "https://www.enr.com/articles/63087-record-16b-data-center-project-advances-in-michigan",
      layer: "projects",
      fly_to: { lat: 42.166, lng: -83.782, zoom: 11 }
    }
  ],
  map_layers: [
    {
      id: "projects",
      label: "Projects",
      description: "Proposed, approved, under construction and operational sites",
      color: "#cf102d",
      default_on: true
    },
    {
      id: "moratoria",
      label: "Moratoria & pauses",
      description: "Local temporary bans and zoning pauses",
      color: "#e09820",
      default_on: true
    },
    {
      id: "meetings",
      label: "Public meetings",
      description: "Upcoming hearings and government sessions",
      color: "#5b9cf5",
      default_on: true
    },
    {
      id: "transmission",
      label: "Power & grid",
      description: "Transmission corridors and grid infrastructure",
      color: "#9c5fc9",
      default_on: true
    },
    {
      id: "policy",
      label: "Capitol & policy",
      description: "State-level rallies, legislation and regulatory actions",
      color: "#22a86a",
      default_on: true
    }
  ],
  transmission_lines: [
    {
      id: "itc-oneida-sabine-route-a",
      name: "ITC Oneida–Sabine Lake (Route A)",
      operator: "ITC Michigan",
      status: "Proposed — route under review",
      voltage: "High voltage",
      length_mi: 50,
      counties: ["Eaton", "Ingham", "Livingston"],
      townships: 15,
      note: "Preliminary route option. MPSC will select final path; site work unlikely before 2027. See official map for parcel-level detail.",
      source_name: "Michigan Public",
      source_url: "https://www.michiganpublic.org/transportation-infrastructure/2025-12-22/routes-proposed-for-high-voltage-transmission-line-in-eaton-ingham-livingston-counties",
      official_map_url: "https://www.mifuturegrid.com/oneida-sabine-lake/",
      coordinates: [
        [42.695, -84.872],
        [42.710, -84.820],
        [42.755, -84.746],
        [42.748, -84.620],
        [42.737, -84.555],
        [42.717, -84.427],
        [42.705, -84.320],
        [42.698, -84.220],
        [42.700, -84.120],
        [42.705, -84.015]
      ]
    },
    {
      id: "itc-oneida-sabine-route-b",
      name: "ITC Oneida–Sabine Lake (Route B)",
      operator: "ITC Michigan",
      status: "Proposed — alternate route",
      voltage: "High voltage",
      length_mi: 50,
      counties: ["Eaton", "Ingham", "Livingston"],
      townships: 15,
      note: "Second preliminary option published by ITC. Community listening sessions held Jan–Feb 2026 across Okemos, Lansing, Holt, Williamston and Fowlerville.",
      source_name: "WKAR Public Media",
      source_url: "https://www.wkar.org/wkar-news/2026-01-25/proposed-transmission-line-would-cross-15-townships-mid-michigan-residents-demand-answers-as-meetings-start-monday",
      official_map_url: "https://www.mifuturegrid.com/oneida-sabine-lake/",
      coordinates: [
        [42.695, -84.872],
        [42.730, -84.780],
        [42.780, -84.650],
        [42.770, -84.520],
        [42.750, -84.400],
        [42.735, -84.280],
        [42.720, -84.150],
        [42.710, -84.050],
        [42.705, -84.015]
      ]
    },
    {
      id: "lbwl-south-reinforcement",
      name: "BWL South Reinforcement (Lansing)",
      operator: "Lansing Board of Water & Light",
      status: "Planned",
      voltage: "Transmission reinforcement",
      length_mi: null,
      counties: ["Ingham"],
      townships: null,
      note: "BWL transmission reinforcement project in the Lansing area — separate from ITC corridor but part of the broader grid build-out discussion around large new loads.",
      source_name: "Lansing BWL",
      source_url: "https://www.lbwl.com/about-bwl/lansing-energy-tomorrow/south-reinforcement-transmission-line-project",
      official_map_url: "https://www.lbwl.com/about-bwl/lansing-energy-tomorrow/south-reinforcement-transmission-line-project",
      coordinates: [
        [42.732, -84.555],
        [42.715, -84.520],
        [42.690, -84.490],
        [42.665, -84.470]
      ]
    }
  ]

};
